# Generated by Django 5.2.5 on 2025-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudHomeApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
    ]
