# Generated by Django 5.2.5 on 2025-09-03 00:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudHomeApi', '0002_house_media_delete_houseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedHome',
            fields=[
                ('saved_home_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='StudHomeApi.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_homes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', 'house'], name='StudHomeApi_user_id_2410d0_idx')],
                'unique_together': {('user', 'house')},
            },
        ),
    ]
